services:
  ai-server:
    container_name: ai-server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./data/ai-server:/app/configs



